
version: 2
# This is an example .goreleaser.yml file with some sensible defaults.
# Make sure to check the documentation at https://goreleaser.com
before:
  hooks:
    # You may remove this if you don't use go modules.
    - go mod tidy
    - go test ./...
builds:
  - env:
      - CGO_ENABLED=0
    goos:
      - darwin
      - linux
    goarch:
      - amd64
      - arm64
    main: main.go
    binary: koi

archives:
  - files:
    - README.md

checksum:
  name_template: 'checksums.txt'

snapshot:
  version_template: "{{ incpatch .Version }}-next"

# From: https://medium.com/@ben.lafferty/deploying-go-cli-applications-316e9cca16a4
brews:
  - repository:
        owner: oliverisaac
        name: homebrew-tap
    directory: Formula
    homepage: https://github.com/oliverisaac/koi
    description: Kubectl wrapper command
    extra_install: |
      bin.install_symlink "koi" => "kcontainers"
      bin.install_symlink "koi" => "kshell"

changelog:
  sort: asc
  filters:
    exclude:
      - '^docs:'
      - '^test:'
      - 'README'
      - Merge pull request
      - Merge branch
